apiVersion: v1
kind: Service
metadata:
 name: vm-service
spec:
 selector:
  app: victoria-metrics 
 ports:
  - name: httpListenAddr
    port: 8428
    targetPort: 8428
  - name: opentsdbListenAddr
    port: 4242
    targetPort: 4242
  - name: graphiteListenAddr
    port: 2003
    targetPort: 2003

